### ISSUE TITLE
WebSocket 超时时间过长

### ISSUE THREAD

**Issue by StephanoGeorge** [moeshin/cx-auto-sign#1]
帐号1输出：

```log
[14:43:58 INF] CXIM: Message received: h
[14:44:23 INF] CXIM: Message received: h
[14:44:48 INF] CXIM: Message received: h
[14:45:13 INF] CXIM: Message received: h
[14:45:38 INF] CXIM: Message received: h
[14:46:03 INF] CXIM: Message received: h
[14:46:28 INF] CXIM: Message received: h
[14:46:53 INF] CXIM: Message received: h
[14:47:18 INF] CXIM: Message received: h
[14:47:43 INF] CXIM: Message received: h
[15:04:02 ERR] [WEBSOCKET CLIENT] Exception while connecting. Waiting 60 sec before next reconnection try. Error: 'Unable to conne
ct to the remote server'
System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
---> System.Net.Sockets.SocketException (104): Connection reset by peer
--- End of inner exception stack trace ---
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToke
n)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter ada
p, ValueTask`1 task, Int32 minSize)
at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthen
ticationData, Boolean isApm)
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions s
slOptions, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
at Websocket.Client.WebsocketClient.<>c__DisplayClass65_0.<<GetClientFactory>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Websocket.Client.WebsocketClient.StartClient(Uri uri, CancellationToken token, ReconnectionType type, Boolean failFast)
[15:05:03 INF] CXIM: Message received: o
[15:05:03 INF] CXIM 登录
```
14:53:40，同班帐号2、3、4收到消息，但帐号1无提示，且未签到。帐号2输出：

```log
[14:53:40 INF] 接收到课程消息
[14:53:40 INF] [1637650420328.1968] 消息时间：1637650420327.6873
```

这些帐号均在同一台机器上运行

运行的脚本版本为 `8fbf8e1433eac8fb2e24d6e80254433fef49f03d`

**Comment by moeshin** [comment]
默认是一分钟超时重连，可能偶尔抽抽风

**Comment by moeshin** [comment]
还有问题吗

**Comment by StephanoGeorge** [comment]
先关闭吧，谢谢
