### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by Epxir** [moeshin/cx-auto-sign#18]
图片是前几次课其他人拍的照片，爬下来的 235kb
Images/机房.png
![截屏2022-04-20 19 40 07](https://user-images.githubusercontent.com/79371047/164223841-123733a4-61bd-4e3a-b094-2d03744a3067.png)

19:11:01 I attActiveType: 0
19:11:01 I aType: 0
19:11:01 I activeType: 2
19:11:01 I 签到类型："图片签到"
19:11:01 E 上传图片失败
System.ArgumentNullException: Value cannot be null. (Parameter 'fileName')
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized) in /_/src/libraries/System.IO.FileSystem/src/System/IO/FileInfo.cs:line 30
   at System.IO.FileInfo..ctor(String fileName) in /_/src/libraries/System.IO.FileSystem/src/System/IO/FileInfo.cs:line 23
   at RestSharp.RestRequest.AddFile(String name, String path, String contentType)
   at CxSignHelper.CxSignClient.UploadImageAsync(String path) in /home/runner/work/cx-auto-sign/cx-auto-sign/CxSignHelper/CxSignClient.cs:line 195
   at cx_auto_sign.SignWork.GetImageIdAsync(CxSignClient client, DateTime now) in /home/runner/work/cx-auto-sign/cx-auto-sign/cx-auto-sign/SignWork.cs:line 105
19:11:01 I 将使用一张黑图进行图片签到

**Comment by moeshin** [comment]
配置写在 `SignPhoto` 里

**Comment by Epxir** [comment]
> 
，，，
start.sh 建议加入开启webapi这样方便的多，测试半天发现开不了

**Comment by Epxir** [comment]
> 配置写在 `SignPhoto` 里

{}和[]是否不一样？，[]随机选值是不是不能同时判断？

**Comment by Epxir** [comment]
> 配置写在 `SignPhoto` 里

两种规则应该是冲突的吧，{}才能逐个判断

**Comment by moeshin** [comment]
`{}` 判断星期时间，`[]` 随机里面的图片

```json5
{
  "SignPhoto": {
    "|am": ["自习室1.jpg", "自习室2.jpg"],
    "|pm": ["自习室3.jpg", "自习室4.jpg"]
  }
}
```

**Comment by Epxir** [comment]
> 配置写在 `SignPhoto` 里
怪不得不能-a ，webapi要是能直接输出所有的就好了，这样省事的多，不用一个一个开端口，网页直接管理开关和看所有人的状态信息

**Comment by moeshin** [comment]
> 怪不得不能-a ，webapi要是能直接输出所有的就好了，这样省事的多，不用一个一个开端口，网页直接管理开关和看所有人的状态信息

#20

**Comment by Epxir** [comment]
![截屏2022-04-29 15 27 00](https://user-images.githubusercontent.com/79371047/165901752-296db63a-7203-4fd9-b131-856433b24d92.png)
所有图片上传不了了，上传到本地正常，但是有个报错
可能是test不能测试上传图片
今天有一个图片没有去判断上传图片，直接黑图了，检查语法无误

**Comment by Epxir** [comment]
@moeshin
