### ISSUE TITLE
获取课程数据失败

### ISSUE THREAD

**Issue by cjw414522569** [moeshin/cx-auto-sign#33]
```text
[00:28:26 INF] 成功登录账号
[00:28:26 INF] 获取课程数据中...
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at CxSignHelper.CxSignClient.GetClassDetailAsync(String courseId, String classId) in /home/runner/work/cx-auto-sign/cx-auto-sign/CxSignHelper/CxSignClient.cs:line 176
   at CxSignHelper.CxSignClient.GetCoursesAsync(JToken course) in /home/runner/work/cx-auto-sign/cx-auto-sign/CxSignHelper/CxSignClient.cs:line 150
   at cx_auto_sign.UserDataConfig.UpdateAsync(CxSignClient client) in /home/runner/work/cx-auto-sign/cx-auto-sign/cx-auto-sign/UserDataConfig.cs:line 131
   at cx_auto_sign.InitCommand.OnExecuteAsync(CommandLineApplication app) in /home/runner/work/cx-auto-sign/cx-auto-sign/cx-auto-sign/InitCommand.cs:line 31
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at cx_auto_sign.Program.Main(String[] args) in /home/runner/work/cx-auto-sign/cx-auto-sign/cx-auto-sign/Program.cs:line 31
   at cx_auto_sign.Program.<Main>(String[] args)
```

**Comment by moeshin** [comment]
该接口已无法获课程与 IM 聊天相应的 chatid

**Comment by moeshin** [comment]
之后可能会用 classid + courseid 代替 chatid

https://github.com/moeshin/cx-auto-sign/blob/67d53b551f2ea964c5e16c06325164ec963d4266/cx-auto-sign/WorkCommand.cs#L361-L364

**Comment by moeshin** [comment]
着急的用话可以康康这两个项目

* [Clansty/superstar-checkin](https://github.com/Clansty/superstar-checkin)
* [cxOrz/chaoxing-sign-cli](https://github.com/cxOrz/chaoxing-sign-cli)

**Comment by Epxir** [comment]
json也改一下，监听单端口获取全部信息就好，前端好写，不用费事了

**Comment by moeshin** [comment]
> json也改一下，监听单端口获取全部信息就好，前端好写，不用费事了

课程配置的键名格式变为：CourseId-ClassId
